spring.application.name=alerta
server.port=8081

# Configuración de Conexión a PostgreSQL (con variables de entorno y fallbacks locales)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/patitas_en_alerta}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres3218}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate (JPA)
# 'update' creará/actualizará las tablas automáticamente según las entidades
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Seguridad Habilitada. (Eliminamos la exclusión temporal del paso 1)
spring.main.allow-bean-definition-overriding=true
